# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/major_system',
                'doc_host': 'https://hgzech.github.io',
                'git_url': 'https://github.com/hgzech/major_system',
                'lib_path': 'major_system'},
  'syms': {'major_system.core': {'major_system.core.foo': ('core.html#foo', 'major_system/core.py')}}}
